export const people = [
  {
    name: "Dr. Phillip Wolff",
    role: "Lab Director",
    image: "/people/wolff.jpg",
    group: "director",
    bio: "Dr. Wolff leads the Language Biomarker Lab, focusing on the computational modeling of language, cognition, and AI reasoning.",
    research: "Cognitive semantics, AI and language modeling, metaphor comprehension",
  },
  {
    name: "Christopher Walsh",
    role: "Senior Software Engineer",
    image: "/people/christopher.png",
    group: "faculty",
    bio: "Christopher builds the lab’s AI infrastructure, focusing on multimodal model development, RAG pipelines, and distributed inference on GPU clusters.",
    research: "Generative AI, cognitive modeling, multimodal LLM systems",
  },
  {
    name: "Annie He",
    role: "Research Software Engineer",
    image: "/people/annie.jpg",
    group: "faculty",
    bio: "Annie designs and maintains the lab’s web infrastructure and visual analytics tools for interpreting language data.",
    research: "Web visualization, cognitive linguistics, interactive data design",
  },
  {
    name: "Benjamin Dixon",
    role: "Research Software Engineer",
    image: "/people/benjamin.jpg",
    group: "faculty",
    bio: "Benjamin develops the computational tools used in language and cognition experiments, supporting data pipelines and ML modeling.",
    research: "Machine learning, experimental linguistics, data visualization",
  },
  {
    name: "Zarina Bilgrami",
    role: "Doctoral Student",
    image: "/people/zarina.jpg",
    group: "phd",
    bio: "Zarina’s research explores linguistic markers of affect and mental health in spontaneous speech.",
    research: "Language biomarkers, psycholinguistics, NLP for healthcare",
  },
  {
    name: "Linying Li",
    role: "Doctoral Student",
    image: "/people/linying.jpg",
    group: "phd",
    bio: "Linying studies computational semantics and language representation learning in human and machine contexts.",
    research: "Cognitive semantics, representation learning, LLM interpretability",
  },
  {
    name: "Nan Jiang",
    role: "Doctoral Student",
    image: "/people/nan.jpg",
    group: "phd",
    bio: "Nan’s research investigates cognitive architectures and symbolic grounding in large language models.",
    research: "Symbolic reasoning, cognitive modeling, LLM architectures",
  },
  {
    name: "Jason Zhang",
    role: "Undergraduate Research Assistant",
    image: "/people/jason.jpg",
    group: "undergrad",
    bio: "Jason assists in data curation, model evaluation, and analysis for large-scale language datasets.",
    research: "Data analysis, machine learning, computational linguistics",
  },
    {
    name: "Maanu Obalapuram",
    role: "Undergraduate Research Assistant",
    image: "/people/maanu.jpg",
    group: "undergrad",
    bio: "Maanu contributes to behavioral data collection and supports ML preprocessing pipelines for language experiments.",
    research: "Cognitive science, linguistics, AI-assisted analysis",
  },
  {
    name: "Ramlah Amer",
    role: "Undergraduate Research Assistant",
    image: "/people/ramlah.jpg",
    group: "undergrad",
    bio: "Ramlah supports research coordination and manages the dataset annotation process for the lab’s AI studies.",
    research: "Computational linguistics, annotation design, applied AI",
  },
];
